# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='open_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='shift date')),
                ('start', models.CharField(max_length=10, verbose_name='start time')),
                ('end', models.CharField(max_length=10, verbose_name='end time')),
                ('description', models.CharField(max_length=200, verbose_name=' description')),
                ('is_filled', models.BooleanField(default=False)),
            ],
        ),
    ]
