# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_shift',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
