# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_open_shift_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_shift',
            name='date',
            field=models.DateField(null=True, verbose_name='shift date'),
        ),
    ]
