# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_auto_20170404_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_shift',
            name='attire',
            field=models.CharField(default='unknown', max_length=200, verbose_name=' attire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open_shift',
            name='filled_by',
            field=models.CharField(max_length=200, null=True, verbose_name='filled by'),
        ),
    ]
