# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_auto_20170407_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_shift',
            name='attire',
            field=models.CharField(max_length=200, verbose_name='attire'),
        ),
        migrations.AlterField(
            model_name='open_shift',
            name='filled_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='filled by'),
        ),
    ]
