# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todvstom', '0002_auto_20170510_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
    ]
