# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todvstom', '0004_auto_20170511_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='set_date',
            field=models.DateField(null=True, verbose_name='set date'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='symph_a',
            field=models.CharField(max_length=200, verbose_name='Symphony A'),
        ),
    ]
