# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todvstom', '0006_auto_20170511_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='beethoven',
            field=models.TextField(default=1, max_length=200, verbose_name='Beethoven'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='board',
            field=models.TextField(default=1, max_length=200, verbose_name='Temple Boardroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='capitol',
            field=models.TextField(default=1, max_length=200, verbose_name='Capitol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='handel',
            field=models.TextField(default=1, max_length=200, verbose_name='Handel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='haydn',
            field=models.TextField(default=1, max_length=200, verbose_name='Haydn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='mozart',
            field=models.TextField(default=1, max_length=200, verbose_name='mozart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='other',
            field=models.TextField(default=1, max_length=200, verbose_name='Other'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='thirty_third',
            field=models.TextField(default=1, max_length=200, verbose_name='33rd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='ballroom',
            field=models.TextField(max_length=200, verbose_name='Ballroom'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='symph_a',
            field=models.TextField(max_length=200, verbose_name='Symphony A'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='symph_b',
            field=models.TextField(max_length=200, verbose_name='Symphony b'),
        ),
    ]
