# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todvstom', '0010_auto_20170512_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='set_date',
            field=models.DateField(blank=True, default='no information available', null=True, unique=True, verbose_name='set date'),
        ),
    ]
