# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todvstom', '0011_auto_20170512_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='set_date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='set date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='symph_a',
            field=models.TextField(blank=True, default='no information \n\n room available', max_length=200, verbose_name='Symphony A'),
        ),
    ]
