# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todvstom', '0012_auto_20170512_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='symph_a',
            field=models.TextField(blank=True, default='\nGROUP:\n\nCONTACT:\n\nTIME:\n\n', max_length=200, verbose_name='Symphony A'),
        ),
    ]
